export default {
  CODE_LENGTH: [1, 2, 3, 4],
  GITHUB_CLIENT_ID: process.env.GITHUB_CLIENT_ID,
  GITHUB_CLIENT_SECRET: process.env.GITHUB_CLIENT_SECRET,
  GITHUB_CALLBACK_URL: process.env.GITHUB_CALLBACK_URL,
  GOOGLE_CLIENT_ID: process.env.GOOGLE_CLIENT_ID,
  GOOGLE_CLIENT_SECRET: process.env.GOOGLE_CLIENT_SECRET,
  GOOGLE_CALLBACK_URL: process.env.GOOGLE_CALLBACK_URL,
  JWT_PRIVATE_KEY: process.env.JWT_PRIVATE_KEY,
  MONGO_URI: process.env.MONGO_URI,
  REDIS_URI: process.env.REDIS_URI,
  REDIS_PORT: process.env.REDIS_PORT,
  REDIS_SESSION_SECRET: process.env.REDIS_SESSION_SECRET,
  REDIS_EXPIRATION: process.env.REDIS_EXPIRATION,
  REDIS_URL: process.env.REDISCLOUD_URL,
  REDIS_LABS_PASSWORD: process.env.REDIS_LABS_PASSWORD
};
